import type { Location } from "@/types/models";

// Real NYC & Long Island ice cream shops for demo purposes
export const DEMO_LOCATIONS: Location[] = [
  {
    id: "1",
    name: "Van Leeuwen Ice Cream",
    slug: "van-leeuwen-east-village",
    location_type: "scoop_shop",
    address_line1: "48 E 7th St",
    city: "New York",
    state: "NY",
    zip: "10003",
    avg_rating: 4.5,
    total_ratings: 342,
    total_checkins: 891,
    is_claimed: true,
    latitude: 40.7267,
    longitude: -73.9876,
    website: "https://vanleeuwenicecream.com",
    instagram: "vanleeuwenicecream",
  },
  {
    id: "2",
    name: "Morgenstern's Finest Ice Cream",
    slug: "morgensterns-finest-lower-east-side",
    location_type: "scoop_shop",
    address_line1: "2 Rivington St",
    city: "New York",
    state: "NY",
    zip: "10002",
    avg_rating: 4.7,
    total_ratings: 289,
    total_checkins: 654,
    is_claimed: true,
    latitude: 40.7206,
    longitude: -73.9932,
    website: "https://morgensternsnyc.com",
  },
  {
    id: "3",
    name: "Ample Hills Creamery",
    slug: "ample-hills-gowanus",
    location_type: "scoop_shop",
    address_line1: "305 Nevins St",
    city: "Brooklyn",
    state: "NY",
    zip: "11215",
    avg_rating: 4.4,
    total_ratings: 412,
    total_checkins: 1023,
    is_claimed: true,
    latitude: 40.6785,
    longitude: -73.9857,
  },
  {
    id: "4",
    name: "Big Gay Ice Cream Shop",
    slug: "big-gay-ice-cream-east-village",
    location_type: "scoop_shop",
    address_line1: "125 E 7th St",
    city: "New York",
    state: "NY",
    zip: "10009",
    avg_rating: 4.3,
    total_ratings: 567,
    total_checkins: 1245,
    is_claimed: true,
    latitude: 40.7261,
    longitude: -73.984,
  },
  {
    id: "5",
    name: "OddFellows Ice Cream Co.",
    slug: "oddfellows-williamsburg",
    location_type: "scoop_shop",
    address_line1: "175 Kent Ave",
    city: "Brooklyn",
    state: "NY",
    zip: "11249",
    avg_rating: 4.6,
    total_ratings: 198,
    total_checkins: 456,
    is_claimed: true,
    latitude: 40.7144,
    longitude: -73.9613,
  },
  {
    id: "6",
    name: "Soft Swerve",
    slug: "soft-swerve-lower-east-side",
    location_type: "scoop_shop",
    address_line1: "85B Allen St",
    city: "New York",
    state: "NY",
    zip: "10002",
    avg_rating: 4.2,
    total_ratings: 321,
    total_checkins: 678,
    is_claimed: false,
    latitude: 40.7183,
    longitude: -73.9903,
  },
  {
    id: "7",
    name: "Trader Joe's - Union Square",
    slug: "trader-joes-union-square",
    location_type: "supermarket",
    address_line1: "142 E 14th St",
    city: "New York",
    state: "NY",
    zip: "10003",
    avg_rating: 3.8,
    total_ratings: 89,
    total_checkins: 234,
    is_claimed: false,
    latitude: 40.7337,
    longitude: -73.9877,
  },
  {
    id: "8",
    name: "Whole Foods Market - Bowery",
    slug: "whole-foods-bowery",
    location_type: "supermarket",
    address_line1: "95 E Houston St",
    city: "New York",
    state: "NY",
    zip: "10002",
    avg_rating: 3.6,
    total_ratings: 67,
    total_checkins: 156,
    is_claimed: false,
    latitude: 40.7242,
    longitude: -73.9916,
  },
  {
    id: "10",
    name: "Davey's Ice Cream",
    slug: "daveys-ice-cream-east-village",
    location_type: "scoop_shop",
    address_line1: "137 1st Ave",
    city: "New York",
    state: "NY",
    zip: "10003",
    avg_rating: 4.4,
    total_ratings: 234,
    total_checkins: 567,
    is_claimed: true,
    latitude: 40.7277,
    longitude: -73.9848,
  },
  {
    id: "11",
    name: "Magic Fountain",
    slug: "magic-fountain-mattituck",
    location_type: "scoop_shop",
    address_line1: "9825 Main Rd",
    city: "Mattituck",
    state: "NY",
    zip: "11952",
    avg_rating: 4.8,
    total_ratings: 156,
    total_checkins: 423,
    is_claimed: false,
    latitude: 40.9913,
    longitude: -72.5335,
  },
  {
    id: "12",
    name: "Snowflake Ice Cream Shoppe",
    slug: "snowflake-riverhead",
    location_type: "scoop_shop",
    address_line1: "76 Flanders Rd",
    city: "Riverhead",
    state: "NY",
    zip: "11901",
    avg_rating: 4.5,
    total_ratings: 201,
    total_checkins: 534,
    is_claimed: false,
    latitude: 40.9168,
    longitude: -72.6882,
  },
  {
    id: "13",
    name: "Jim & Rob's Fresh Squeez'd",
    slug: "jim-robs-huntington",
    location_type: "scoop_shop",
    address_line1: "265 New York Ave",
    city: "Huntington",
    state: "NY",
    zip: "11743",
    avg_rating: 4.6,
    total_ratings: 178,
    total_checkins: 445,
    is_claimed: false,
    latitude: 40.8718,
    longitude: -73.4257,
  },
  {
    id: "14",
    name: "Salt & Straw",
    slug: "salt-and-straw-larchmont",
    location_type: "scoop_shop",
    address_line1: "171 Larchmont Ave",
    city: "New York",
    state: "NY",
    zip: "10011",
    avg_rating: 4.5,
    total_ratings: 256,
    total_checkins: 612,
    is_claimed: true,
    latitude: 40.7421,
    longitude: -74.0003,
  },
  {
    id: "15",
    name: "Jeni's Splendid Ice Creams",
    slug: "jenis-splendid-greenwich-village",
    location_type: "scoop_shop",
    address_line1: "130 W 3rd St",
    city: "New York",
    state: "NY",
    zip: "10012",
    avg_rating: 4.3,
    total_ratings: 312,
    total_checkins: 789,
    is_claimed: true,
    latitude: 40.7308,
    longitude: -74.0003,
  },
];
